import turtle 
tt = turtle.Turtle()    
screen=turtle.Screen()    
screen.setup(1200,600)    
screen.bgcolor('alice blue')    
tt.pencolor('blue')    
tt.pensize(12)    
tt.speed(1)    
tt.shape('turtle')   
tt.backward(120)    
tt.left(100) 
tt.backward(120)
tt.left(90)
tt.backward(140)   
tt.left(90)
tt.backward(120)
tt.right(120)
tt.forward(140)
tt.penup() 
tt.setpos(-120,120) 
tt.pendown()
tt.pencolor('green')
tt.write('Never Back Down', font=("Arial", 20, "bold"))
tt.penup()
tt.ht()
